export const HELP_TEXT = [
	"🤖 Chronos — Command Reference",
	"",
	"⏰ REMINDERS",
	"/remind 2026-09-15 10:00 [message]",
	"/remind +7 09:00 [message]",
	"/remind every monday 09:00 [message]",
	"/remind every month 1 10:00 [message]",
	"/remind every day 08:00 [message]",
	"/remind yearly 09-15 09:00 [message]",
	"/list (reminders)",
	"/delete [id]",
	"",
	"📝 NOTES",
	"/note [text]",
	"/note +3d [text]",
	"/notes",
	"/delete note [id]",
	"",
	"📎 DOCUMENTS",
	"Send any file with caption to save",
	"/files",
	"/recall [id]",
	"/delete doc [id]",
	"",
	"🔖 BOOKMARKS",
	"Send any URL with label to save",
	"/bookmark [url] [label]",
	"/bookmarks",
	"/recall bookmark [id]",
	"/delete bookmark [id]",
	"",
	"✅ TO-DO LISTS",
	"/list create [name]",
	"/list add [name] [items]",
	"/list show [name]",
	"/list remind [name] [date] [time]",
	"/list remind [name] [item#] [date] [time]",
	"/lists",
	"/list done [name]",
	"/list delete [name]",
	"",
	"🔍 SEARCH",
	"/search [keywords]",
	"",
	"📊 DASHBOARD",
	"/summary",
].join("\n");
